/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BattleArenaOptimized {
  export type BattleStruct = {
    battleId: BigNumberish;
    battleType: BigNumberish;
    participants: [BigNumberish, BigNumberish];
    players: [AddressLike, AddressLike];
    state: BigNumberish;
    winner: BigNumberish;
    prizePool: BigNumberish;
    timestamp: BigNumberish;
  };

  export type BattleStructOutput = [
    battleId: bigint,
    battleType: bigint,
    participants: [bigint, bigint],
    players: [string, string],
    state: bigint,
    winner: bigint,
    prizePool: bigint,
    timestamp: bigint
  ] & {
    battleId: bigint;
    battleType: bigint;
    participants: [bigint, bigint];
    players: [string, string];
    state: bigint;
    winner: bigint;
    prizePool: bigint;
    timestamp: bigint;
  };
}

export interface BattleArenaOptimizedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "artifactContract"
      | "battles"
      | "createDuel"
      | "duelFee"
      | "emergencyFreeMolanimal"
      | "getBattle"
      | "getBattleInfo"
      | "getPlayerBattles"
      | "monanimalContract"
      | "monanimalInBattle"
      | "owner"
      | "playerBattles"
      | "renounceOwnership"
      | "setContracts"
      | "setFees"
      | "tournamentFee"
      | "transferOwnership"
      | "weaponContract"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BattleCompleted"
      | "BattleCreated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "artifactContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "battles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDuel",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "duelFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyFreeMolanimal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBattle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBattleInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerBattles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monanimalContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "monanimalInBattle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerBattles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setContracts",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tournamentFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "weaponContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "artifactContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "battles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createDuel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "duelFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyFreeMolanimal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBattle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBattleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerBattles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monanimalContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monanimalInBattle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerBattles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tournamentFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "weaponContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BattleCompletedEvent {
  export type InputTuple = [
    battleId: BigNumberish,
    winner: BigNumberish,
    prizePool: BigNumberish
  ];
  export type OutputTuple = [
    battleId: bigint,
    winner: bigint,
    prizePool: bigint
  ];
  export interface OutputObject {
    battleId: bigint;
    winner: bigint;
    prizePool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleCreatedEvent {
  export type InputTuple = [
    battleId: BigNumberish,
    participant1: BigNumberish,
    participant2: BigNumberish
  ];
  export type OutputTuple = [
    battleId: bigint,
    participant1: bigint,
    participant2: bigint
  ];
  export interface OutputObject {
    battleId: bigint;
    participant1: bigint;
    participant2: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BattleArenaOptimized extends BaseContract {
  connect(runner?: ContractRunner | null): BattleArenaOptimized;
  waitForDeployment(): Promise<this>;

  interface: BattleArenaOptimizedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  artifactContract: TypedContractMethod<[], [string], "view">;

  battles: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        battleId: bigint;
        battleType: bigint;
        state: bigint;
        winner: bigint;
        prizePool: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  createDuel: TypedContractMethod<
    [myMonanimalId: BigNumberish, opponentMonanimalId: BigNumberish],
    [void],
    "payable"
  >;

  duelFee: TypedContractMethod<[], [bigint], "view">;

  emergencyFreeMolanimal: TypedContractMethod<
    [monanimalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBattle: TypedContractMethod<
    [battleId: BigNumberish],
    [BattleArenaOptimized.BattleStructOutput],
    "view"
  >;

  getBattleInfo: TypedContractMethod<
    [battleId: BigNumberish],
    [
      [[bigint, bigint], [string, string], bigint, bigint, bigint] & {
        participants: [bigint, bigint];
        players: [string, string];
        winner: bigint;
        prizePool: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  getPlayerBattles: TypedContractMethod<
    [player: AddressLike],
    [bigint[]],
    "view"
  >;

  monanimalContract: TypedContractMethod<[], [string], "view">;

  monanimalInBattle: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  playerBattles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setContracts: TypedContractMethod<
    [
      _monanimalContract: AddressLike,
      _weaponContract: AddressLike,
      _artifactContract: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setFees: TypedContractMethod<
    [_duelFee: BigNumberish, _tournamentFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  tournamentFee: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  weaponContract: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "artifactContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "battles"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        battleId: bigint;
        battleType: bigint;
        state: bigint;
        winner: bigint;
        prizePool: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createDuel"
  ): TypedContractMethod<
    [myMonanimalId: BigNumberish, opponentMonanimalId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "duelFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyFreeMolanimal"
  ): TypedContractMethod<[monanimalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBattle"
  ): TypedContractMethod<
    [battleId: BigNumberish],
    [BattleArenaOptimized.BattleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBattleInfo"
  ): TypedContractMethod<
    [battleId: BigNumberish],
    [
      [[bigint, bigint], [string, string], bigint, bigint, bigint] & {
        participants: [bigint, bigint];
        players: [string, string];
        winner: bigint;
        prizePool: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerBattles"
  ): TypedContractMethod<[player: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "monanimalContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "monanimalInBattle"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playerBattles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setContracts"
  ): TypedContractMethod<
    [
      _monanimalContract: AddressLike,
      _weaponContract: AddressLike,
      _artifactContract: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [_duelFee: BigNumberish, _tournamentFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tournamentFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "weaponContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BattleCompleted"
  ): TypedContractEvent<
    BattleCompletedEvent.InputTuple,
    BattleCompletedEvent.OutputTuple,
    BattleCompletedEvent.OutputObject
  >;
  getEvent(
    key: "BattleCreated"
  ): TypedContractEvent<
    BattleCreatedEvent.InputTuple,
    BattleCreatedEvent.OutputTuple,
    BattleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BattleCompleted(uint256,uint256,uint256)": TypedContractEvent<
      BattleCompletedEvent.InputTuple,
      BattleCompletedEvent.OutputTuple,
      BattleCompletedEvent.OutputObject
    >;
    BattleCompleted: TypedContractEvent<
      BattleCompletedEvent.InputTuple,
      BattleCompletedEvent.OutputTuple,
      BattleCompletedEvent.OutputObject
    >;

    "BattleCreated(uint256,uint256,uint256)": TypedContractEvent<
      BattleCreatedEvent.InputTuple,
      BattleCreatedEvent.OutputTuple,
      BattleCreatedEvent.OutputObject
    >;
    BattleCreated: TypedContractEvent<
      BattleCreatedEvent.InputTuple,
      BattleCreatedEvent.OutputTuple,
      BattleCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
