/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as monanimalNftUpdatedSol from "./MonanimalNFT_Updated.sol";
export { ArtifactNFT__factory } from "./ArtifactNFT__factory";
export { BattleArena__factory } from "./BattleArena__factory";
export { BattleArenaOptimized__factory } from "./BattleArenaOptimized__factory";
export { MonanimalNFT__factory } from "./MonanimalNFT__factory";
export { WeaponNFT__factory } from "./WeaponNFT__factory";
