/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as monanimalNftImprovedSol from "./MonanimalNFT_Improved.sol";
export type { monanimalNftImprovedSol };
import type * as monanimalNftUpdatedSol from "./MonanimalNFT_Updated.sol";
export type { monanimalNftUpdatedSol };
export type { ArtifactNFT } from "./ArtifactNFT";
export type { BattleArena } from "./BattleArena";
export type { BattleArenaOptimized } from "./BattleArenaOptimized";
export type { MonanimalNFT } from "./MonanimalNFT";
export type { TestSVGGenerator } from "./TestSVGGenerator";
export type { TestSVGGenerator_Improved } from "./TestSVGGenerator_Improved";
export type { WeaponNFT } from "./WeaponNFT";
